#!/usr/bin/env bash
#
# Generates the QA stand info page (config/qa/stand.html) from config/platform.conf.
# Called by up.sh / set-version.sh when QA_TOOLS_ENABLED=true; safe to run standalone too.
# Only whitelisted fields are read below - never dump platform.conf wholesale (it also holds
# SECRET, payment/push/LLM keys).

set -euo pipefail

CONFIG_DIR="config"
CONFIG_FILE="$CONFIG_DIR/platform.conf"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "Config not found: $CONFIG_FILE. Run ./setup.sh first."
    exit 1
fi
# shellcheck disable=SC1090
source "$CONFIG_FILE"

mkdir -p "$CONFIG_DIR/qa"

esc() {
    printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' -e 's/"/\&quot;/g'
}
onoff() { [ "${1:-}" == "true" ] && echo "on" || echo "off"; }

PROTOCOL=$([ -n "${SECURE:-}" ] && echo "https" || echo "http")
FRONT_URL="${PROTOCOL}://${HOST_ADDRESS}"

AI_BOT_STATE="off"
[ -n "${LLM_MODE:-}" ] && [ "$LLM_MODE" != "none" ] && AI_BOT_STATE="on (${LLM_MODE})"

# Compose services of the currently active profiles - same profile flags as up.sh.
DC="docker compose --env-file config/platform.conf"
if [ "${DEV_MODE:-}" == "true" ] && [ -f "dev/compose.override.yml" ]; then
    DC="$DC -f compose.yml -f dev/compose.override.yml"
    [ "${LIVEKIT_ENABLED:-}" == "true" ] && DC="$DC --profile livekit-dev"
elif [ "${LIVEKIT_ENABLED:-}" == "true" ]; then
    DC="$DC --profile livekit"
fi
[ "${PAYMENT_PROVIDER:-}" == "tbank" ] && DC="$DC --profile tbank"
[ "${WEBHOOK_ENABLED:-}" == "true" ] && DC="$DC --profile webhook"
[ "${OAITT_ENABLED:-}" == "true" ] && DC="$DC --profile stt"
DC="$DC --profile qa"
SERVICES=$($DC config --services 2>/dev/null | sort | tr '\n' ' ') || SERVICES=""

# Postgres is the only DB service in compose.yml; -A20 covers its short block without a YAML parser.
PG_BLOCK=$(grep -A20 '^  postgres:' compose.yml || true)
PG_IMAGE=$(printf '%s\n' "$PG_BLOCK" | grep -m1 'image:' | awk '{print $2}')
PG_PUBLISHED=false
printf '%s\n' "$PG_BLOCK" | grep -q '5432:5432' && PG_PUBLISHED=true

PG_INTERNAL_URL="postgres://$(esc "$POSTGRES_USER"):$(esc "$POSTGRES_PASSWORD")@postgres:5432/$(esc "$POSTGRES_DB")"
if [ "$PG_PUBLISHED" == true ]; then
    PG_EXTERNAL_BLOCK="<pre>postgres://$(esc "$POSTGRES_USER"):$(esc "$POSTGRES_PASSWORD")@$(esc "$HOST_ADDRESS"):5432/$(esc "$POSTGRES_DB")</pre>"
else
    PG_EXTERNAL_BLOCK="<pre>docker compose --env-file config/platform.conf exec -it postgres psql -U $(esc "$POSTGRES_USER") -d $(esc "$POSTGRES_DB")</pre>"
fi

cat > "$CONFIG_DIR/qa/stand.html" <<HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>$(esc "${TITLE:-Intabia Platform}") - Stand Info</title>
<style>
body { font-family: -apple-system, sans-serif; max-width: 760px; margin: 2rem auto; padding: 0 1rem; color: #222; }
h1 { font-size: 1.4rem; } h2 { font-size: 1.1rem; margin-top: 2rem; border-bottom: 1px solid #ddd; }
table { border-collapse: collapse; width: 100%; } td { padding: .25rem .5rem; vertical-align: top; }
td:first-child { color: #666; width: 12rem; }
pre { background: #f4f4f4; padding: .75rem; overflow-x: auto; }
code { background: #f4f4f4; padding: .1rem .3rem; }
</style>
</head>
<body>
<h1>$(esc "${TITLE:-Intabia Platform}") - Stand Info</h1>
<p>Generated by qa-info.sh. Read-only, for test stands only.</p>

<h2>Platform</h2>
<table>
<tr><td>Version</td><td>$(esc "${PLATFORM_VERSION:-}")</td></tr>
<tr><td>URL</td><td><a href="$(esc "$FRONT_URL")">$(esc "$FRONT_URL")</a></td></tr>
<tr><td>Image registry</td><td>$(esc "${IMAGE_PREFIX:-intabiafusion}")</td></tr>
<tr><td>SSL</td><td>$([ -n "${SECURE:-}" ] && echo on || echo off)</td></tr>
<tr><td>LiveKit</td><td>$(onoff "${LIVEKIT_ENABLED:-}")</td></tr>
<tr><td>Webhook</td><td>$(onoff "${WEBHOOK_ENABLED:-}")</td></tr>
<tr><td>Payment provider</td><td>$(esc "${PAYMENT_PROVIDER:-mock}")</td></tr>
<tr><td>AI bot</td><td>$(esc "$AI_BOT_STATE")</td></tr>
<tr><td>Logs</td><td><a href="/_logs">/_logs</a> (Dozzle)</td></tr>
<tr><td>Active services</td><td>$(esc "${SERVICES:-unavailable}")</td></tr>
</table>

<h2>PostgreSQL</h2>
<table>
<tr><td>Service / image</td><td>postgres ($(esc "${PG_IMAGE:-unknown}"))</td></tr>
<tr><td>Port</td><td>5432 (published on host: $([ "$PG_PUBLISHED" == true ] && echo yes || echo no))</td></tr>
<tr><td>User</td><td>$(esc "$POSTGRES_USER")</td></tr>
<tr><td>Database</td><td>$(esc "$POSTGRES_DB")</td></tr>
<tr><td>Password</td><td>$(esc "$POSTGRES_PASSWORD")</td></tr>
</table>
<p>From inside the docker network:</p>
<pre>$PG_INTERNAL_URL</pre>
<p>From a QA machine:</p>
$PG_EXTERNAL_BLOCK

<h2>MinIO</h2>
<table>
<tr><td>Console</td><td><a href="http://$(esc "$HOST_ADDRESS"):9001">http://$(esc "$HOST_ADDRESS"):9001</a></td></tr>
<tr><td>S3 API</td><td>http://$(esc "$HOST_ADDRESS"):9000</td></tr>
<tr><td>User / password</td><td>minioadmin / minioadmin</td></tr>
<tr><td>Buckets</td><td>blobs (workspace files), backups (backup service and archives), chunks</td></tr>
</table>
<p>Published by compose.qa.yml only while QA tools are on.</p>
</body>
</html>
HTML
